import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import PasteContext from './lib/context/PasteContext';
import { Toaster } from '@/components/ui/toaster';
import dbConnect from './db/dbconnect';
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Share Paste',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect();
  return (
    <html lang="en">
      <body className={inter.className}>
        <PasteContext>
          <main>
            {children}
            <Analytics />
          </main>
          <Toaster />
        </PasteContext>
      </body>
    </html>
  );
}
